version: '3.4'
services:
  db: 
    image: mariadb:10.3.22
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: seila123
      MYSQL_DATABASE: springboot
    ports:
      - "3308:3306"
    networks:
      - udemy-networks
  springboot-application:
    image: springboot-application
    restart: always
    build: ./springboot
    working_dir: ./springboot
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    links:
      - db
    depends_on: 
      - db
    networks: 
      - udemy-networks
networks:
    udemy-networks:
        driver: bridge